// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMassaNodeInstallation():Promise<string>;

export function CheckMassaNodeStatus():Promise<string>;

export function ConnectToServer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function DisconnectFromServer():Promise<string>;

export function GetServerStats():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RunCommand(arg1:string):Promise<string>;

export function SetupAndRunMassaComponents(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StartMassaNode(arg1:string):Promise<string>;
