// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectToServer'](arg1, arg2, arg3, arg4);
}

export function DisconnectFromServer() {
  return window['go']['main']['App']['DisconnectFromServer']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallMassaNode(arg1, arg2) {
  return window['go']['main']['App']['InstallMassaNode'](arg1, arg2);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}
