// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMassaNodeInstallation() {
  return window['go']['main']['App']['CheckMassaNodeInstallation']();
}

export function CheckMassaNodeStatus() {
  return window['go']['main']['App']['CheckMassaNodeStatus']();
}

export function ConnectToServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectToServer'](arg1, arg2, arg3, arg4);
}

export function DisconnectFromServer() {
  return window['go']['main']['App']['DisconnectFromServer']();
}

export function GetMassaNodeLogs() {
  return window['go']['main']['App']['GetMassaNodeLogs']();
}

export function GetServerStats() {
  return window['go']['main']['App']['GetServerStats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SetupAndRunMassaComponents(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupAndRunMassaComponents'](arg1, arg2, arg3);
}

export function StartMassaNode(arg1) {
  return window['go']['main']['App']['StartMassaNode'](arg1);
}
