// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToServer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function DisconnectFromServer():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallMassaNode(arg1:string,arg2:string):Promise<string>;

export function RunCommand(arg1:string):Promise<string>;
